{"name": "Создание курьера с повторными данными", "status": "passed", "description": "Проверяем создание курьера с использованием уже существующих данных и получаем ошибку", "steps": [{"name": "Cоздание двух курьеров с одиннаковыми данными", "status": "passed", "parameters": [{"name": "payload", "value": "{'login': 'Annette Lewis', 'password': 'juN9cCSn^3', 'first_name': 'Tina'}"}], "start": 1720981675016, "stop": 1720981675311}], "start": 1720981675016, "stop": 1720981675311, "uuid": "4391108a-42d4-4993-b8a9-64cbecc20beb", "historyId": "2819b86dc4245a249da8ad4e3ba120ef", "testCaseId": "2819b86dc4245a249da8ad4e3ba120ef", "fullName": "tests.test_create_courier.TestCourierCreateAPI#test_create_already_existing_courier_fail", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_create_courier"}, {"name": "subSuite", "value": "TestCourierCreateAPI"}, {"name": "host", "value": "DESKTOP-LQ0DQPC"}, {"name": "thread", "value": "17576-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_courier"}]}